"""APT-managed CMND 0.8 activation.

Versioned Debian packages place tooling, exact Philips inputs and pinned Tomcat
on disk first. This module inventories the host, selects coexistence modes,
prepares runtime images and hands activation to coexist_deploy. Database admin
passwords are accepted only through root-only temporary files and never persisted.
"""
from __future__ import annotations
import argparse, json, os, re, shutil, socket, subprocess, tempfile
from pathlib import Path
from . import __version__
from .config import ConfigError, load_config
from .coexist_deploy import CoexistInputs, deploy
from .environment import DEFAULT_PORTS, host_inventory
from .install_plan import allocate_port, build_plan
from .native_deploy import BASELINE, MYSQL_IMAGE, validate_baseline
from .shared_database import SharedDatabaseSession

VENDOR_ROOT=Path('/usr/lib/cmnd/vendor/7.5.9')
TOMCAT_ARCHIVE=Path('/usr/lib/cmnd/tomcat/apache-tomcat-9.0.121.tar.gz')
PACKAGE_ARCHIVE=Path(f'/usr/lib/cmnd/packages/linux-cmnd_{__version__}_amd64.deb')
DEFAULT_CONFIG=Path('/opt/linux-cmnd/current/config/cmnd.install.toml')
CONFIG=Path('/etc/cmnd/cmnd.toml'); CACHE=Path('/var/cache/linux-cmnd/bootstrap')
PHP_IID=CACHE/'php-image.id'; PHP_BUILD_LOG=CACHE/'php-build.log'

def _run(args,*,timeout=1800): return subprocess.run(args,capture_output=True,timeout=timeout,check=False)
def _require_root():
    if os.name!='posix' or not hasattr(os,'geteuid') or os.geteuid()!=0: raise ConfigError('APT activation must run as root')
def _safe_password_file(path):
    path=Path(path)
    if not path.is_file() or path.is_symlink() or any(p.is_symlink() for p in path.parents): raise ConfigError('database administrator password file must be a regular non-symlink file')
    if path.stat().st_size>4096 or (os.name=='posix' and path.stat().st_mode&0o077): raise ConfigError('database administrator password file must be mode 0600 or stricter')
    value=path.read_text(encoding='utf-8').rstrip('\r\n')
    if not value or any(c in value for c in ('\x00','\n','\r')): raise ConfigError('database administrator password is empty or contains unsupported control characters')
    return value
def _option_quote(value): return '"'+value.replace('\\','\\\\').replace('"','\\"')+'"'
def _db_defaults_file(directory,user,password):
    if not re.fullmatch(r'[A-Za-z0-9_@.-]{1,64}',user): raise ConfigError('invalid database administrator username')
    path=directory/'database-admin.cnf'; fd=os.open(path,os.O_CREAT|os.O_EXCL|os.O_WRONLY,0o600)
    with os.fdopen(fd,'w',encoding='utf-8',newline='\n') as h:h.write(f'[client]\nuser={_option_quote(user)}\npassword={_option_quote(password)}\n')
    return path

def _assigned_ipv4():
    r=_run(['ip','-j','-4','address','show'],timeout=10)
    if r.returncode:return []
    try:interfaces=json.loads(r.stdout)
    except Exception:return []
    return [a['local'] for i in interfaces if 'UP' in i.get('flags',[]) for a in i.get('addr_info',[]) if a.get('family')=='inet' and isinstance(a.get('local'),str)]
def choose_server_ip(requested=None):
    assigned=_assigned_ipv4()
    if requested:
        try:socket.inet_aton(requested)
        except OSError as e:raise ConfigError('server IP must be a literal IPv4 address') from e
        if requested!='127.0.0.1' and requested not in assigned: raise ConfigError('requested server IP is not assigned to an active local interface')
        return requested
    values=[v for v in assigned if not v.startswith('127.')]; return values[0] if values else '127.0.0.1'
def _occupied(inv): return {int(x['port']) for x in inv.get('listeners',{}).get('entries',[]) if isinstance(x,dict) and isinstance(x.get('port'),int)}
def _planned_ports(inv,plan,database_mode):
    c=plan['components']; ports={'tomcat_http':int(c['tomcat']['ports']['http']),'tomcat_https':int(c['tomcat']['ports']['https']),'apache_http':int(c['apache']['ports']['http']),'apache_https':int(c['apache']['ports']['https'])}
    if database_mode=='shared':ports['database']=int(c['database'].get('port') or DEFAULT_PORTS['database'])
    else:ports['database']=allocate_port(DEFAULT_PORTS['database'],_occupied(inv),set(ports.values())|{DEFAULT_PORTS['php_fpm'],DEFAULT_PORTS['management']})
    if len(set(ports.values())|{DEFAULT_PORTS['php_fpm'],DEFAULT_PORTS['management']})!=7: raise ConfigError('installation planner produced colliding CMND ports')
    return ports
def render_config(ip,ports):
    mode='isolated' if ip.startswith('127.') else 'lab'
    return f'''# Generated by CMND Linux 0.8 APT activation. No TVs are authorized.\n[safety]\nmode = "{mode}"\npermitted_ranges = ["127.0.0.0/8"]\n\n[network]\nbind = "{ip}"\ncallback_base_url = "http://{ip}:{ports['tomcat_http']}"\ntimeout_seconds = 5\n\n[ports]\ntomcat_http = {ports['tomcat_http']}\ntomcat_https = {ports['tomcat_https']}\napache_http = {ports['apache_http']}\napache_https = {ports['apache_https']}\ndatabase = {ports['database']}\n\n[tv]\nallowlist = []\n'''
def _install_config(content):
    CONFIG.parent.mkdir(mode=0o750,parents=True,exist_ok=True)
    if CONFIG.exists() or CONFIG.is_symlink():
        if CONFIG.is_symlink() or not CONFIG.is_file():raise ConfigError('existing CMND configuration path is unsafe')
        if DEFAULT_CONFIG.is_file() and CONFIG.read_bytes()!=DEFAULT_CONFIG.read_bytes():load_config(CONFIG); return CONFIG
        backup=CONFIG.with_name('cmnd.toml.package-default')
        if not backup.exists():backup.write_bytes(CONFIG.read_bytes()); backup.chmod(0o600)
    temp=CONFIG.with_name('.cmnd.toml.apt-new')
    if temp.exists() or temp.is_symlink():raise ConfigError('stale temporary CMND configuration exists')
    fd=os.open(temp,os.O_CREAT|os.O_EXCL|os.O_WRONLY,0o640)
    with os.fdopen(fd,'w',encoding='utf-8',newline='\n') as h:h.write(content)
    os.replace(temp,CONFIG); load_config(CONFIG); return CONFIG
def _find_db_client(inv):
    db=inv.get('database',{})
    for name in ('mariadb_client','mysql_client'):
        r=db.get(name,{})
        if isinstance(r,dict) and r.get('present') and r.get('path'):return str(r['path'])
    return shutil.which('mariadb') or shutil.which('mysql')
def _shared_session(inv,password_file,admin_user,temp):
    client=_find_db_client(inv)
    if not client:return None
    db=inv.get('database',{}); sockets=db.get('socket_candidates') or []
    if db.get('root_socket_auth')=='available' and sockets and admin_user=='root':s=SharedDatabaseSession(client,3306,socket_path=str(sockets[0]),admin_user='root')
    elif password_file is not None:s=SharedDatabaseSession(client,3306,socket_path=str(sockets[0]) if sockets else None,admin_defaults_file=_db_defaults_file(temp,admin_user,_safe_password_file(password_file)),admin_user=admin_user)
    else:return None
    try:
        port=s.execute('SELECT @@port;',timeout=10).decode(errors='replace').strip()
        if port.isdigit():s.port=int(port)
    except RuntimeError:return None
    return s
def _select_modes(inv,plan,requested_database,requested_apache,password_file,admin_user,temp):
    notes=[]; session=None
    if requested_database in {'auto','existing'}:
        session=_shared_session(inv,password_file,admin_user,temp)
        if session:
            try:session.validate_for_fresh_cmnd(); dbmode='shared'; notes.append('Existing MySQL passed shared-database gate.')
            except (ConfigError,RuntimeError) as e:
                if requested_database=='existing':raise
                session=None; dbmode='isolated'; notes.append('Existing database preserved but not reused: '+str(e))
        elif requested_database=='existing':raise ConfigError('existing database mode requested but no authenticated administrator session is available')
        else:dbmode='isolated'; notes.append('No qualified authenticated host DB; using isolated MySQL fallback.')
    elif requested_database=='isolated':dbmode='isolated'
    else:raise ConfigError('database mode must be auto, existing, or isolated')
    ap=inv.get('web',{}).get('apache_service',{}); present=bool(plan['components']['apache'].get('existing_apache'))
    if requested_apache=='auto':webmode='host' if present and ap.get('active') else 'standalone'
    elif requested_apache in {'host','standalone'}:webmode=requested_apache
    else:raise ConfigError('Apache mode must be auto, host, or standalone')
    if webmode=='host' and not present:raise ConfigError('host Apache mode requested but no existing Apache installation was detected')
    notes.append('Apache mode: '+webmode); return dbmode,webmode,session,notes
def _ensure_docker():
    if not shutil.which('docker'):raise ConfigError('Docker runtime is required by current legacy PHP profile')
    r=_run(['docker','info'],timeout=20)
    if r.returncode and shutil.which('systemctl'):_run(['systemctl','enable','--now','docker.service'],timeout=120); r=_run(['docker','info'],timeout=20)
    if r.returncode:raise ConfigError('Docker daemon unavailable')
def _ensure_image(image):
    if _run(['docker','image','inspect',image],timeout=30).returncode==0:return
    if _run(['docker','pull',image],timeout=1800).returncode:raise ConfigError('required pinned container image could not be pulled')
def _php_image():
    if PHP_IID.is_file() and not PHP_IID.is_symlink():
        image=PHP_IID.read_text().strip()
        if image and _run(['docker','image','inspect',image],timeout=30).returncode==0:return image
    CACHE.mkdir(parents=True,mode=0o700,exist_ok=True); dockerfile=Path('/opt/linux-cmnd/current/deploy/php/Dockerfile.lab'); context=dockerfile.parent
    if not dockerfile.is_file():raise ConfigError('packaged legacy PHP Dockerfile is missing')
    partial=PHP_IID.with_suffix('.partial'); partial.unlink(missing_ok=True)
    with PHP_BUILD_LOG.open('wb') as log:r=subprocess.run(['docker','build','-f',str(dockerfile),'--iidfile',str(partial),str(context)],stdout=log,stderr=subprocess.STDOUT,timeout=3600,check=False)
    if r.returncode or not partial.is_file():raise ConfigError('legacy PHP image build failed; inspect /var/cache/linux-cmnd/bootstrap/php-build.log')
    image=partial.read_text().strip()
    if not re.fullmatch(r'sha256:[0-9a-f]{64}',image):raise ConfigError('unexpected PHP image identifier')
    os.replace(partial,PHP_IID); PHP_IID.chmod(0o600); PHP_BUILD_LOG.chmod(0o600); return image
def _install_baseline():
    if not PACKAGE_ARCHIVE.is_file() or PACKAGE_ARCHIVE.is_symlink():raise ConfigError('matching rollback package is missing from cmnd-linux')
    CACHE.mkdir(parents=True,mode=0o700,exist_ok=True)
    if BASELINE.is_symlink():raise ConfigError('rollback package path is unsafe symlink')
    if not BASELINE.exists():shutil.copyfile(PACKAGE_ARCHIVE,BASELINE); BASELINE.chmod(0o600)
    validate_baseline()
def plan(server_ip=None,database_mode='auto',apache_mode='auto',password_file=None,admin_user='root'):
    inv=host_inventory(); base=build_plan(inv)
    if not base.get('fresh_install_allowed'):raise ConfigError('existing active CMND runtime detected')
    with tempfile.TemporaryDirectory(prefix='cmnd-apt-plan-') as d:
        db,web,session,notes=_select_modes(inv,base,database_mode,apache_mode,password_file,admin_user,Path(d)); ports=_planned_ports(inv,base,db)
        if db=='shared':ports['database']=session.port
        return {'schema':1,'executed':False,'server_ip':choose_server_ip(server_ip),'database_mode':db,'apache_mode':web,'ports':ports,'notes':notes,'base_plan':base,'shared_database_qualified':db=='shared'}
def activate(server_ip,database_mode,apache_mode,password_file,admin_user,execute,accept_legacy):
    if not execute:return plan(server_ip,database_mode,apache_mode,password_file,admin_user)
    _require_root()
    if not accept_legacy:raise ConfigError('legacy PHP 5.6/MySQL 5.7 runtime acceptance is required')
    if not VENDOR_ROOT.is_dir() or VENDOR_ROOT.is_symlink():raise ConfigError('verified Philips vendor package is not installed')
    if not TOMCAT_ARCHIVE.is_file() or TOMCAT_ARCHIVE.is_symlink():raise ConfigError('pinned CMND Tomcat package is not installed')
    inv=host_inventory(); base=build_plan(inv)
    if not base.get('fresh_install_allowed'):raise ConfigError('existing active CMND runtime detected; use upgrade workflow')
    os.umask(0o077)
    with tempfile.TemporaryDirectory(prefix='cmnd-apt-admin-',dir='/run' if Path('/run').is_dir() else None) as d:
        db,web,session,notes=_select_modes(inv,base,database_mode,apache_mode,password_file,admin_user,Path(d)); ports=_planned_ports(inv,base,db)
        if db=='shared':ports['database']=session.port
        address=choose_server_ip(server_ip); config=_install_config(render_config(address,ports)); cfg=load_config(config)
        if db=='shared' and cfg.database_port!=session.port:raise ConfigError('preserved config DB port does not match shared server')
        _ensure_docker(); _ensure_image(MYSQL_IMAGE) if db=='isolated' else None; php=_php_image(); _install_baseline()
        result=deploy(CoexistInputs(config,VENDOR_ROOT,TOMCAT_ARCHIVE,php,Path('/usr/lib/jvm/java-17-openjdk-amd64'),db,web,session,True),execute=True,accept_legacy=True)
        result['apt_activation']={'server_ip':address,'database_mode':db,'apache_mode':web,'notes':notes}; return result
def main(argv=None):
    p=argparse.ArgumentParser(prog='cmndctl apt-activate'); p.add_argument('--server-ip'); p.add_argument('--database-mode',choices=('auto','existing','isolated'),default='auto'); p.add_argument('--apache-mode',choices=('auto','host','standalone'),default='auto'); p.add_argument('--database-admin-user',default='root'); p.add_argument('--database-admin-password-file',type=Path); p.add_argument('--accept-legacy-runtime',action='store_true'); p.add_argument('--execute',action='store_true'); p.add_argument('--dry-run',action='store_true'); a=p.parse_args(argv)
    try:r=activate(a.server_ip,a.database_mode,a.apache_mode,a.database_admin_password_file,a.database_admin_user,a.execute and not a.dry_run,a.accept_legacy_runtime)
    except (ConfigError,RuntimeError,OSError,subprocess.SubprocessError) as e:print('cmndctl apt-activate: '+str(e),file=os.sys.stderr); return 2
    print(json.dumps(r,indent=2,sort_keys=True)); return 0
