namespace DTAPINET;

public enum DtDvbT2RbmEventType
{
	PLOT,
	DJB_UNDERFLOW,
	BUFS_TOO_SMALL,
	TTO_IN_THE_PAST,
	DJB_OVERFLOW,
	CRC8_ERROR_HEADER,
	DFL_TOO_LARGE,
	SYNCD_TOO_LARGE,
	INVALID_UPL,
	INVALID_SYNCD,
	TDI_OVERFLOW,
	TOO_MANY_TI_BLOCKS,
	INVALID_PLP_START,
	FDI_OVERFLOW,
	NO_TS_RATE,
	ISCR_ERROR,
	BUFS_NOT_CONSTANT,
	ISSYI_NOT_CONSTANT,
	HEM_NOT_CONSTANT,
	PLP_NUM_BLOCKS_TOO_SMALL
}
