namespace DTAPINET;

public enum DtFirmwareStatus
{
	DTAPI_FWSTATUS_UNDEFINED = -1,
	DTAPI_FWSTATUS_UPTODATE,
	DTAPI_FWSTATUS_BETA,
	DTAPI_FWSTATUS_OLD,
	DTAPI_FWSTATUS_NEW,
	DTAPI_FWSTATUS_TAINTED,
	DTAPI_FWSTATUS_OBSOLETE
}
