namespace DTAPINET;

public enum DtStreamType
{
	STREAM_CONSTEL = 3,
	STREAM_ATSC3 = 1,
	STREAM_ATSC3_BBFRAME = 2,
	STREAM_DAB = 4,
	STREAM_DABETI = 5,
	STREAM_DABFIC = 6,
	STREAM_DVBC2 = 7,
	STREAM_DVBC2_BBFRAME = 8,
	STREAM_DVBT = 12,
	STREAM_DVBT2 = 13,
	STREAM_DVBT2_BBFRAME = 14,
	STREAM_DVBT2_GSE = 15,
	STREAM_IMPRESP = 16,
	STREAM_ISDBT = 17,
	STREAM_MER = 18,
	STREAM_SPECTRUM = 20,
	STREAM_T2MI = 21,
	STREAM_TF_ABS = 22,
	STREAM_TF_PHASE = 23,
	STREAM_TF_GROUPDELAY = 24,
	STREAM_TXID_IMPRESP = 25
}
