package be.tpvision.smartcontrol.codecs.sicp188.miscellaneous;

import be.tpvision.smartcontrol.codecs.sicp.SingleValueCodec;
import be.tpvision.smartcontrol.domain.device_settings.miscellaneous.SwitchOnDelay;
import be.tpvision.smartcontrol.messages.codecs.sicp188.miscellaneous.switch_on_delay.FillSwitchOnDelaysMessages;
import java.util.EnumMap;
import java.util.Map;
import org.springframework.util.Assert;

public class SwitchOnDelayCodec extends SingleValueCodec<SwitchOnDelay> {
   static final byte OFF_BYTE = 0;
   static final byte AUTO_BYTE = 1;
   static final byte _2_SECONDS_BYTE = 2;
   static final byte _3_SECONDS_BYTE = 3;
   static final byte _4_SECONDS_BYTE = 4;
   static final byte _5_SECONDS_BYTE = 5;
   static final byte _6_SECONDS_BYTE = 6;
   static final byte _7_SECONDS_BYTE = 7;
   static final byte _8_SECONDS_BYTE = 8;
   static final byte _9_SECONDS_BYTE = 9;
   static final byte _10_SECONDS_BYTE = 10;
   static final byte _11_SECONDS_BYTE = 11;
   static final byte _12_SECONDS_BYTE = 12;
   static final byte _13_SECONDS_BYTE = 13;
   static final byte _14_SECONDS_BYTE = 14;
   static final byte _15_SECONDS_BYTE = 15;
   static final byte _16_SECONDS_BYTE = 16;
   static final byte _17_SECONDS_BYTE = 17;
   static final byte _18_SECONDS_BYTE = 18;
   static final byte _19_SECONDS_BYTE = 19;
   static final byte _20_SECONDS_BYTE = 20;
   static final byte _21_SECONDS_BYTE = 21;
   static final byte _22_SECONDS_BYTE = 22;
   static final byte _23_SECONDS_BYTE = 23;
   static final byte _24_SECONDS_BYTE = 24;
   static final byte _25_SECONDS_BYTE = 25;
   static final byte _26_SECONDS_BYTE = 26;
   static final byte _27_SECONDS_BYTE = 27;
   static final byte _28_SECONDS_BYTE = 28;
   static final byte _29_SECONDS_BYTE = 29;
   static final byte _30_SECONDS_BYTE = 30;
   static final byte _31_SECONDS_BYTE = 31;
   static final byte _32_SECONDS_BYTE = 32;
   static final byte _33_SECONDS_BYTE = 33;
   static final byte _34_SECONDS_BYTE = 34;
   static final byte _35_SECONDS_BYTE = 35;
   static final byte _36_SECONDS_BYTE = 36;
   static final byte _37_SECONDS_BYTE = 37;
   static final byte _38_SECONDS_BYTE = 38;
   static final byte _39_SECONDS_BYTE = 39;
   static final byte _40_SECONDS_BYTE = 40;
   static final byte _41_SECONDS_BYTE = 41;
   static final byte _42_SECONDS_BYTE = 42;
   static final byte _43_SECONDS_BYTE = 43;
   static final byte _44_SECONDS_BYTE = 44;
   static final byte _45_SECONDS_BYTE = 45;
   static final byte _46_SECONDS_BYTE = 46;
   static final byte _47_SECONDS_BYTE = 47;
   static final byte _48_SECONDS_BYTE = 48;
   static final byte _49_SECONDS_BYTE = 49;
   static final byte _50_SECONDS_BYTE = 50;
   static final byte _51_SECONDS_BYTE = 51;
   static final byte _52_SECONDS_BYTE = 52;
   static final byte _53_SECONDS_BYTE = 53;
   static final byte _54_SECONDS_BYTE = 54;
   static final byte _55_SECONDS_BYTE = 55;
   static final byte _56_SECONDS_BYTE = 56;
   static final byte _57_SECONDS_BYTE = 57;
   static final byte _58_SECONDS_BYTE = 58;
   static final byte _59_SECONDS_BYTE = 59;
   static final byte _60_SECONDS_BYTE = 60;
   static final byte _61_SECONDS_BYTE = 61;
   static final byte _62_SECONDS_BYTE = 62;
   static final byte _63_SECONDS_BYTE = 63;
   static final byte _64_SECONDS_BYTE = 64;
   static final byte _65_SECONDS_BYTE = 65;
   static final byte _66_SECONDS_BYTE = 66;
   static final byte _67_SECONDS_BYTE = 67;
   static final byte _68_SECONDS_BYTE = 68;
   static final byte _69_SECONDS_BYTE = 69;
   static final byte _70_SECONDS_BYTE = 70;
   static final byte _71_SECONDS_BYTE = 71;
   static final byte _72_SECONDS_BYTE = 72;
   static final byte _73_SECONDS_BYTE = 73;
   static final byte _74_SECONDS_BYTE = 74;
   static final byte _75_SECONDS_BYTE = 75;
   static final byte _76_SECONDS_BYTE = 76;
   static final byte _77_SECONDS_BYTE = 77;
   static final byte _78_SECONDS_BYTE = 78;
   static final byte _79_SECONDS_BYTE = 79;
   static final byte _80_SECONDS_BYTE = 80;
   static final byte _81_SECONDS_BYTE = 81;
   static final byte _82_SECONDS_BYTE = 82;
   static final byte _83_SECONDS_BYTE = 83;
   static final byte _84_SECONDS_BYTE = 84;
   static final byte _85_SECONDS_BYTE = 85;
   static final byte _86_SECONDS_BYTE = 86;
   static final byte _87_SECONDS_BYTE = 87;
   static final byte _88_SECONDS_BYTE = 88;
   static final byte _89_SECONDS_BYTE = 89;
   static final byte _90_SECONDS_BYTE = 90;
   static final byte _91_SECONDS_BYTE = 91;
   static final byte _92_SECONDS_BYTE = 92;
   static final byte _93_SECONDS_BYTE = 93;
   static final byte _94_SECONDS_BYTE = 94;
   static final byte _95_SECONDS_BYTE = 95;
   static final byte _96_SECONDS_BYTE = 96;
   static final byte _97_SECONDS_BYTE = 97;
   static final byte _98_SECONDS_BYTE = 98;
   static final byte _99_SECONDS_BYTE = 99;
   static final byte _100_SECONDS_BYTE = 100;
   static final byte _101_SECONDS_BYTE = 101;
   static final byte _102_SECONDS_BYTE = 102;
   static final byte _103_SECONDS_BYTE = 103;
   static final byte _104_SECONDS_BYTE = 104;
   static final byte _105_SECONDS_BYTE = 105;
   static final byte _106_SECONDS_BYTE = 106;
   static final byte _107_SECONDS_BYTE = 107;
   static final byte _108_SECONDS_BYTE = 108;
   static final byte _109_SECONDS_BYTE = 109;
   static final byte _110_SECONDS_BYTE = 110;
   static final byte _111_SECONDS_BYTE = 111;
   static final byte _112_SECONDS_BYTE = 112;
   static final byte _113_SECONDS_BYTE = 113;
   static final byte _114_SECONDS_BYTE = 114;
   static final byte _115_SECONDS_BYTE = 115;
   static final byte _116_SECONDS_BYTE = 116;
   static final byte _117_SECONDS_BYTE = 117;
   static final byte _118_SECONDS_BYTE = 118;
   static final byte _119_SECONDS_BYTE = 119;
   static final byte _120_SECONDS_BYTE = 120;
   static final byte _121_SECONDS_BYTE = 121;
   static final byte _122_SECONDS_BYTE = 122;
   static final byte _123_SECONDS_BYTE = 123;
   static final byte _124_SECONDS_BYTE = 124;
   static final byte _125_SECONDS_BYTE = 125;
   static final byte _126_SECONDS_BYTE = 126;
   static final byte _127_SECONDS_BYTE = 127;
   static final byte _128_SECONDS_BYTE = -128;
   static final byte _129_SECONDS_BYTE = -127;
   static final byte _130_SECONDS_BYTE = -126;
   static final byte _131_SECONDS_BYTE = -125;
   static final byte _132_SECONDS_BYTE = -124;
   static final byte _133_SECONDS_BYTE = -123;
   static final byte _134_SECONDS_BYTE = -122;
   static final byte _135_SECONDS_BYTE = -121;
   static final byte _136_SECONDS_BYTE = -120;
   static final byte _137_SECONDS_BYTE = -119;
   static final byte _138_SECONDS_BYTE = -118;
   static final byte _139_SECONDS_BYTE = -117;
   static final byte _140_SECONDS_BYTE = -116;
   static final byte _141_SECONDS_BYTE = -115;
   static final byte _142_SECONDS_BYTE = -114;
   static final byte _143_SECONDS_BYTE = -113;
   static final byte _144_SECONDS_BYTE = -112;
   static final byte _145_SECONDS_BYTE = -111;
   static final byte _146_SECONDS_BYTE = -110;
   static final byte _147_SECONDS_BYTE = -109;
   static final byte _148_SECONDS_BYTE = -108;
   static final byte _149_SECONDS_BYTE = -107;
   static final byte _150_SECONDS_BYTE = -106;
   static final byte _151_SECONDS_BYTE = -105;
   static final byte _152_SECONDS_BYTE = -104;
   static final byte _153_SECONDS_BYTE = -103;
   static final byte _154_SECONDS_BYTE = -102;
   static final byte _155_SECONDS_BYTE = -101;
   static final byte _156_SECONDS_BYTE = -100;
   static final byte _157_SECONDS_BYTE = -99;
   static final byte _158_SECONDS_BYTE = -98;
   static final byte _159_SECONDS_BYTE = -97;
   static final byte _160_SECONDS_BYTE = -96;
   static final byte _161_SECONDS_BYTE = -95;
   static final byte _162_SECONDS_BYTE = -94;
   static final byte _163_SECONDS_BYTE = -93;
   static final byte _164_SECONDS_BYTE = -92;
   static final byte _165_SECONDS_BYTE = -91;
   static final byte _166_SECONDS_BYTE = -90;
   static final byte _167_SECONDS_BYTE = -89;
   static final byte _168_SECONDS_BYTE = -88;
   static final byte _169_SECONDS_BYTE = -87;
   static final byte _170_SECONDS_BYTE = -86;
   static final byte _171_SECONDS_BYTE = -85;
   static final byte _172_SECONDS_BYTE = -84;
   static final byte _173_SECONDS_BYTE = -83;
   static final byte _174_SECONDS_BYTE = -82;
   static final byte _175_SECONDS_BYTE = -81;
   static final byte _176_SECONDS_BYTE = -80;
   static final byte _177_SECONDS_BYTE = -79;
   static final byte _178_SECONDS_BYTE = -78;
   static final byte _179_SECONDS_BYTE = -77;
   static final byte _180_SECONDS_BYTE = -76;
   static final byte _181_SECONDS_BYTE = -75;
   static final byte _182_SECONDS_BYTE = -74;
   static final byte _183_SECONDS_BYTE = -73;
   static final byte _184_SECONDS_BYTE = -72;
   static final byte _185_SECONDS_BYTE = -71;
   static final byte _186_SECONDS_BYTE = -70;
   static final byte _187_SECONDS_BYTE = -69;
   static final byte _188_SECONDS_BYTE = -68;
   static final byte _189_SECONDS_BYTE = -67;
   static final byte _190_SECONDS_BYTE = -66;
   static final byte _191_SECONDS_BYTE = -65;
   static final byte _192_SECONDS_BYTE = -64;
   static final byte _193_SECONDS_BYTE = -63;
   static final byte _194_SECONDS_BYTE = -62;
   static final byte _195_SECONDS_BYTE = -61;
   static final byte _196_SECONDS_BYTE = -60;
   static final byte _197_SECONDS_BYTE = -59;
   static final byte _198_SECONDS_BYTE = -58;
   static final byte _199_SECONDS_BYTE = -57;
   static final byte _200_SECONDS_BYTE = -56;
   static final byte _201_SECONDS_BYTE = -55;
   static final byte _202_SECONDS_BYTE = -54;
   static final byte _203_SECONDS_BYTE = -53;
   static final byte _204_SECONDS_BYTE = -52;
   static final byte _205_SECONDS_BYTE = -51;
   static final byte _206_SECONDS_BYTE = -50;
   static final byte _207_SECONDS_BYTE = -49;
   static final byte _208_SECONDS_BYTE = -48;
   static final byte _209_SECONDS_BYTE = -47;
   static final byte _210_SECONDS_BYTE = -46;
   static final byte _211_SECONDS_BYTE = -45;
   static final byte _212_SECONDS_BYTE = -44;
   static final byte _213_SECONDS_BYTE = -43;
   static final byte _214_SECONDS_BYTE = -42;
   static final byte _215_SECONDS_BYTE = -41;
   static final byte _216_SECONDS_BYTE = -40;
   static final byte _217_SECONDS_BYTE = -39;
   static final byte _218_SECONDS_BYTE = -38;
   static final byte _219_SECONDS_BYTE = -37;
   static final byte _220_SECONDS_BYTE = -36;
   static final byte _221_SECONDS_BYTE = -35;
   static final byte _222_SECONDS_BYTE = -34;
   static final byte _223_SECONDS_BYTE = -33;
   static final byte _224_SECONDS_BYTE = -32;
   static final byte _225_SECONDS_BYTE = -31;
   static final byte _226_SECONDS_BYTE = -30;
   static final byte _227_SECONDS_BYTE = -29;
   static final byte _228_SECONDS_BYTE = -28;
   static final byte _229_SECONDS_BYTE = -27;
   static final byte _230_SECONDS_BYTE = -26;
   static final byte _231_SECONDS_BYTE = -25;
   static final byte _232_SECONDS_BYTE = -24;
   static final byte _233_SECONDS_BYTE = -23;
   static final byte _234_SECONDS_BYTE = -22;
   static final byte _235_SECONDS_BYTE = -21;
   static final byte _236_SECONDS_BYTE = -20;
   static final byte _237_SECONDS_BYTE = -19;
   static final byte _238_SECONDS_BYTE = -18;
   static final byte _239_SECONDS_BYTE = -17;
   static final byte _240_SECONDS_BYTE = -16;
   static final byte _241_SECONDS_BYTE = -15;
   static final byte _242_SECONDS_BYTE = -14;
   static final byte _243_SECONDS_BYTE = -13;
   static final byte _244_SECONDS_BYTE = -12;
   static final byte _245_SECONDS_BYTE = -11;
   static final byte _246_SECONDS_BYTE = -10;
   static final byte _247_SECONDS_BYTE = -9;
   static final byte _248_SECONDS_BYTE = -8;
   static final byte _249_SECONDS_BYTE = -7;
   static final byte _250_SECONDS_BYTE = -6;
   static final byte _251_SECONDS_BYTE = -5;
   static final byte _252_SECONDS_BYTE = -4;
   static final byte _253_SECONDS_BYTE = -3;
   static final byte _254_SECONDS_BYTE = -2;
   static final byte _255_SECONDS_BYTE = -1;
   private static SwitchOnDelayCodec switchOnDelayCodec;

   private SwitchOnDelayCodec() {
      super(SwitchOnDelay.class);
   }

   public static synchronized SwitchOnDelayCodec getInstance() {
      if (switchOnDelayCodec == null) {
         switchOnDelayCodec = new SwitchOnDelayCodec();
      }

      return switchOnDelayCodec;
   }

   @Override
   protected void initializeDeviceSettings() {
      Map<SwitchOnDelay, Byte> domainSwitchOnDelays = new EnumMap<>(SwitchOnDelay.class);
      this.fillSwitchOnDelays(domainSwitchOnDelays);
      super.setDeviceSettings(domainSwitchOnDelays);
   }

   private void fillSwitchOnDelays(final Map<SwitchOnDelay, Byte> domainSwitchOnDelays) {
      Assert.notNull(domainSwitchOnDelays, FillSwitchOnDelaysMessages.DOMAIN_SWITCH_ON_DELAYS_CAN_NOT_BE_NULL);
      domainSwitchOnDelays.put(SwitchOnDelay.OFF, (byte)0);
      domainSwitchOnDelays.put(SwitchOnDelay.AUTO, (byte)1);
      domainSwitchOnDelays.put(SwitchOnDelay._2_SECONDS, (byte)2);
      domainSwitchOnDelays.put(SwitchOnDelay._3_SECONDS, (byte)3);
      domainSwitchOnDelays.put(SwitchOnDelay._4_SECONDS, (byte)4);
      domainSwitchOnDelays.put(SwitchOnDelay._5_SECONDS, (byte)5);
      domainSwitchOnDelays.put(SwitchOnDelay._6_SECONDS, (byte)6);
      domainSwitchOnDelays.put(SwitchOnDelay._7_SECONDS, (byte)7);
      domainSwitchOnDelays.put(SwitchOnDelay._8_SECONDS, (byte)8);
      domainSwitchOnDelays.put(SwitchOnDelay._9_SECONDS, (byte)9);
      domainSwitchOnDelays.put(SwitchOnDelay._10_SECONDS, (byte)10);
      domainSwitchOnDelays.put(SwitchOnDelay._11_SECONDS, (byte)11);
      domainSwitchOnDelays.put(SwitchOnDelay._12_SECONDS, (byte)12);
      domainSwitchOnDelays.put(SwitchOnDelay._13_SECONDS, (byte)13);
      domainSwitchOnDelays.put(SwitchOnDelay._14_SECONDS, (byte)14);
      domainSwitchOnDelays.put(SwitchOnDelay._15_SECONDS, (byte)15);
      domainSwitchOnDelays.put(SwitchOnDelay._16_SECONDS, (byte)16);
      domainSwitchOnDelays.put(SwitchOnDelay._17_SECONDS, (byte)17);
      domainSwitchOnDelays.put(SwitchOnDelay._18_SECONDS, (byte)18);
      domainSwitchOnDelays.put(SwitchOnDelay._19_SECONDS, (byte)19);
      domainSwitchOnDelays.put(SwitchOnDelay._20_SECONDS, (byte)20);
      domainSwitchOnDelays.put(SwitchOnDelay._21_SECONDS, (byte)21);
      domainSwitchOnDelays.put(SwitchOnDelay._22_SECONDS, (byte)22);
      domainSwitchOnDelays.put(SwitchOnDelay._23_SECONDS, (byte)23);
      domainSwitchOnDelays.put(SwitchOnDelay._24_SECONDS, (byte)24);
      domainSwitchOnDelays.put(SwitchOnDelay._25_SECONDS, (byte)25);
      domainSwitchOnDelays.put(SwitchOnDelay._26_SECONDS, (byte)26);
      domainSwitchOnDelays.put(SwitchOnDelay._27_SECONDS, (byte)27);
      domainSwitchOnDelays.put(SwitchOnDelay._28_SECONDS, (byte)28);
      domainSwitchOnDelays.put(SwitchOnDelay._29_SECONDS, (byte)29);
      domainSwitchOnDelays.put(SwitchOnDelay._30_SECONDS, (byte)30);
      domainSwitchOnDelays.put(SwitchOnDelay._31_SECONDS, (byte)31);
      domainSwitchOnDelays.put(SwitchOnDelay._32_SECONDS, (byte)32);
      domainSwitchOnDelays.put(SwitchOnDelay._33_SECONDS, (byte)33);
      domainSwitchOnDelays.put(SwitchOnDelay._34_SECONDS, (byte)34);
      domainSwitchOnDelays.put(SwitchOnDelay._35_SECONDS, (byte)35);
      domainSwitchOnDelays.put(SwitchOnDelay._36_SECONDS, (byte)36);
      domainSwitchOnDelays.put(SwitchOnDelay._37_SECONDS, (byte)37);
      domainSwitchOnDelays.put(SwitchOnDelay._38_SECONDS, (byte)38);
      domainSwitchOnDelays.put(SwitchOnDelay._39_SECONDS, (byte)39);
      domainSwitchOnDelays.put(SwitchOnDelay._40_SECONDS, (byte)40);
      domainSwitchOnDelays.put(SwitchOnDelay._41_SECONDS, (byte)41);
      domainSwitchOnDelays.put(SwitchOnDelay._42_SECONDS, (byte)42);
      domainSwitchOnDelays.put(SwitchOnDelay._43_SECONDS, (byte)43);
      domainSwitchOnDelays.put(SwitchOnDelay._44_SECONDS, (byte)44);
      domainSwitchOnDelays.put(SwitchOnDelay._45_SECONDS, (byte)45);
      domainSwitchOnDelays.put(SwitchOnDelay._46_SECONDS, (byte)46);
      domainSwitchOnDelays.put(SwitchOnDelay._47_SECONDS, (byte)47);
      domainSwitchOnDelays.put(SwitchOnDelay._48_SECONDS, (byte)48);
      domainSwitchOnDelays.put(SwitchOnDelay._49_SECONDS, (byte)49);
      domainSwitchOnDelays.put(SwitchOnDelay._50_SECONDS, (byte)50);
      domainSwitchOnDelays.put(SwitchOnDelay._51_SECONDS, (byte)51);
      domainSwitchOnDelays.put(SwitchOnDelay._52_SECONDS, (byte)52);
      domainSwitchOnDelays.put(SwitchOnDelay._53_SECONDS, (byte)53);
      domainSwitchOnDelays.put(SwitchOnDelay._54_SECONDS, (byte)54);
      domainSwitchOnDelays.put(SwitchOnDelay._55_SECONDS, (byte)55);
      domainSwitchOnDelays.put(SwitchOnDelay._56_SECONDS, (byte)56);
      domainSwitchOnDelays.put(SwitchOnDelay._57_SECONDS, (byte)57);
      domainSwitchOnDelays.put(SwitchOnDelay._58_SECONDS, (byte)58);
      domainSwitchOnDelays.put(SwitchOnDelay._59_SECONDS, (byte)59);
      domainSwitchOnDelays.put(SwitchOnDelay._60_SECONDS, (byte)60);
      domainSwitchOnDelays.put(SwitchOnDelay._61_SECONDS, (byte)61);
      domainSwitchOnDelays.put(SwitchOnDelay._62_SECONDS, (byte)62);
      domainSwitchOnDelays.put(SwitchOnDelay._63_SECONDS, (byte)63);
      domainSwitchOnDelays.put(SwitchOnDelay._64_SECONDS, (byte)64);
      domainSwitchOnDelays.put(SwitchOnDelay._65_SECONDS, (byte)65);
      domainSwitchOnDelays.put(SwitchOnDelay._66_SECONDS, (byte)66);
      domainSwitchOnDelays.put(SwitchOnDelay._67_SECONDS, (byte)67);
      domainSwitchOnDelays.put(SwitchOnDelay._68_SECONDS, (byte)68);
      domainSwitchOnDelays.put(SwitchOnDelay._69_SECONDS, (byte)69);
      domainSwitchOnDelays.put(SwitchOnDelay._70_SECONDS, (byte)70);
      domainSwitchOnDelays.put(SwitchOnDelay._71_SECONDS, (byte)71);
      domainSwitchOnDelays.put(SwitchOnDelay._72_SECONDS, (byte)72);
      domainSwitchOnDelays.put(SwitchOnDelay._73_SECONDS, (byte)73);
      domainSwitchOnDelays.put(SwitchOnDelay._74_SECONDS, (byte)74);
      domainSwitchOnDelays.put(SwitchOnDelay._75_SECONDS, (byte)75);
      domainSwitchOnDelays.put(SwitchOnDelay._76_SECONDS, (byte)76);
      domainSwitchOnDelays.put(SwitchOnDelay._77_SECONDS, (byte)77);
      domainSwitchOnDelays.put(SwitchOnDelay._78_SECONDS, (byte)78);
      domainSwitchOnDelays.put(SwitchOnDelay._79_SECONDS, (byte)79);
      domainSwitchOnDelays.put(SwitchOnDelay._80_SECONDS, (byte)80);
      domainSwitchOnDelays.put(SwitchOnDelay._81_SECONDS, (byte)81);
      domainSwitchOnDelays.put(SwitchOnDelay._82_SECONDS, (byte)82);
      domainSwitchOnDelays.put(SwitchOnDelay._83_SECONDS, (byte)83);
      domainSwitchOnDelays.put(SwitchOnDelay._84_SECONDS, (byte)84);
      domainSwitchOnDelays.put(SwitchOnDelay._85_SECONDS, (byte)85);
      domainSwitchOnDelays.put(SwitchOnDelay._86_SECONDS, (byte)86);
      domainSwitchOnDelays.put(SwitchOnDelay._87_SECONDS, (byte)87);
      domainSwitchOnDelays.put(SwitchOnDelay._88_SECONDS, (byte)88);
      domainSwitchOnDelays.put(SwitchOnDelay._89_SECONDS, (byte)89);
      domainSwitchOnDelays.put(SwitchOnDelay._90_SECONDS, (byte)90);
      domainSwitchOnDelays.put(SwitchOnDelay._91_SECONDS, (byte)91);
      domainSwitchOnDelays.put(SwitchOnDelay._92_SECONDS, (byte)92);
      domainSwitchOnDelays.put(SwitchOnDelay._93_SECONDS, (byte)93);
      domainSwitchOnDelays.put(SwitchOnDelay._94_SECONDS, (byte)94);
      domainSwitchOnDelays.put(SwitchOnDelay._95_SECONDS, (byte)95);
      domainSwitchOnDelays.put(SwitchOnDelay._96_SECONDS, (byte)96);
      domainSwitchOnDelays.put(SwitchOnDelay._97_SECONDS, (byte)97);
      domainSwitchOnDelays.put(SwitchOnDelay._98_SECONDS, (byte)98);
      domainSwitchOnDelays.put(SwitchOnDelay._99_SECONDS, (byte)99);
      domainSwitchOnDelays.put(SwitchOnDelay._100_SECONDS, (byte)100);
      domainSwitchOnDelays.put(SwitchOnDelay._101_SECONDS, (byte)101);
      domainSwitchOnDelays.put(SwitchOnDelay._102_SECONDS, (byte)102);
      domainSwitchOnDelays.put(SwitchOnDelay._103_SECONDS, (byte)103);
      domainSwitchOnDelays.put(SwitchOnDelay._104_SECONDS, (byte)104);
      domainSwitchOnDelays.put(SwitchOnDelay._105_SECONDS, (byte)105);
      domainSwitchOnDelays.put(SwitchOnDelay._106_SECONDS, (byte)106);
      domainSwitchOnDelays.put(SwitchOnDelay._107_SECONDS, (byte)107);
      domainSwitchOnDelays.put(SwitchOnDelay._108_SECONDS, (byte)108);
      domainSwitchOnDelays.put(SwitchOnDelay._109_SECONDS, (byte)109);
      domainSwitchOnDelays.put(SwitchOnDelay._110_SECONDS, (byte)110);
      domainSwitchOnDelays.put(SwitchOnDelay._111_SECONDS, (byte)111);
      domainSwitchOnDelays.put(SwitchOnDelay._112_SECONDS, (byte)112);
      domainSwitchOnDelays.put(SwitchOnDelay._113_SECONDS, (byte)113);
      domainSwitchOnDelays.put(SwitchOnDelay._114_SECONDS, (byte)114);
      domainSwitchOnDelays.put(SwitchOnDelay._115_SECONDS, (byte)115);
      domainSwitchOnDelays.put(SwitchOnDelay._116_SECONDS, (byte)116);
      domainSwitchOnDelays.put(SwitchOnDelay._117_SECONDS, (byte)117);
      domainSwitchOnDelays.put(SwitchOnDelay._118_SECONDS, (byte)118);
      domainSwitchOnDelays.put(SwitchOnDelay._119_SECONDS, (byte)119);
      domainSwitchOnDelays.put(SwitchOnDelay._120_SECONDS, (byte)120);
      domainSwitchOnDelays.put(SwitchOnDelay._121_SECONDS, (byte)121);
      domainSwitchOnDelays.put(SwitchOnDelay._122_SECONDS, (byte)122);
      domainSwitchOnDelays.put(SwitchOnDelay._123_SECONDS, (byte)123);
      domainSwitchOnDelays.put(SwitchOnDelay._124_SECONDS, (byte)124);
      domainSwitchOnDelays.put(SwitchOnDelay._125_SECONDS, (byte)125);
      domainSwitchOnDelays.put(SwitchOnDelay._126_SECONDS, (byte)126);
      domainSwitchOnDelays.put(SwitchOnDelay._127_SECONDS, (byte)127);
      domainSwitchOnDelays.put(SwitchOnDelay._128_SECONDS, (byte)-128);
      domainSwitchOnDelays.put(SwitchOnDelay._129_SECONDS, (byte)-127);
      domainSwitchOnDelays.put(SwitchOnDelay._130_SECONDS, (byte)-126);
      domainSwitchOnDelays.put(SwitchOnDelay._131_SECONDS, (byte)-125);
      domainSwitchOnDelays.put(SwitchOnDelay._132_SECONDS, (byte)-124);
      domainSwitchOnDelays.put(SwitchOnDelay._133_SECONDS, (byte)-123);
      domainSwitchOnDelays.put(SwitchOnDelay._134_SECONDS, (byte)-122);
      domainSwitchOnDelays.put(SwitchOnDelay._135_SECONDS, (byte)-121);
      domainSwitchOnDelays.put(SwitchOnDelay._136_SECONDS, (byte)-120);
      domainSwitchOnDelays.put(SwitchOnDelay._137_SECONDS, (byte)-119);
      domainSwitchOnDelays.put(SwitchOnDelay._138_SECONDS, (byte)-118);
      domainSwitchOnDelays.put(SwitchOnDelay._139_SECONDS, (byte)-117);
      domainSwitchOnDelays.put(SwitchOnDelay._140_SECONDS, (byte)-116);
      domainSwitchOnDelays.put(SwitchOnDelay._141_SECONDS, (byte)-115);
      domainSwitchOnDelays.put(SwitchOnDelay._142_SECONDS, (byte)-114);
      domainSwitchOnDelays.put(SwitchOnDelay._143_SECONDS, (byte)-113);
      domainSwitchOnDelays.put(SwitchOnDelay._144_SECONDS, (byte)-112);
      domainSwitchOnDelays.put(SwitchOnDelay._145_SECONDS, (byte)-111);
      domainSwitchOnDelays.put(SwitchOnDelay._146_SECONDS, (byte)-110);
      domainSwitchOnDelays.put(SwitchOnDelay._147_SECONDS, (byte)-109);
      domainSwitchOnDelays.put(SwitchOnDelay._148_SECONDS, (byte)-108);
      domainSwitchOnDelays.put(SwitchOnDelay._149_SECONDS, (byte)-107);
      domainSwitchOnDelays.put(SwitchOnDelay._150_SECONDS, (byte)-106);
      domainSwitchOnDelays.put(SwitchOnDelay._151_SECONDS, (byte)-105);
      domainSwitchOnDelays.put(SwitchOnDelay._152_SECONDS, (byte)-104);
      domainSwitchOnDelays.put(SwitchOnDelay._153_SECONDS, (byte)-103);
      domainSwitchOnDelays.put(SwitchOnDelay._154_SECONDS, (byte)-102);
      domainSwitchOnDelays.put(SwitchOnDelay._155_SECONDS, (byte)-101);
      domainSwitchOnDelays.put(SwitchOnDelay._156_SECONDS, (byte)-100);
      domainSwitchOnDelays.put(SwitchOnDelay._157_SECONDS, (byte)-99);
      domainSwitchOnDelays.put(SwitchOnDelay._158_SECONDS, (byte)-98);
      domainSwitchOnDelays.put(SwitchOnDelay._159_SECONDS, (byte)-97);
      domainSwitchOnDelays.put(SwitchOnDelay._160_SECONDS, (byte)-96);
      domainSwitchOnDelays.put(SwitchOnDelay._161_SECONDS, (byte)-95);
      domainSwitchOnDelays.put(SwitchOnDelay._162_SECONDS, (byte)-94);
      domainSwitchOnDelays.put(SwitchOnDelay._163_SECONDS, (byte)-93);
      domainSwitchOnDelays.put(SwitchOnDelay._164_SECONDS, (byte)-92);
      domainSwitchOnDelays.put(SwitchOnDelay._165_SECONDS, (byte)-91);
      domainSwitchOnDelays.put(SwitchOnDelay._166_SECONDS, (byte)-90);
      domainSwitchOnDelays.put(SwitchOnDelay._167_SECONDS, (byte)-89);
      domainSwitchOnDelays.put(SwitchOnDelay._168_SECONDS, (byte)-88);
      domainSwitchOnDelays.put(SwitchOnDelay._169_SECONDS, (byte)-87);
      domainSwitchOnDelays.put(SwitchOnDelay._170_SECONDS, (byte)-86);
      domainSwitchOnDelays.put(SwitchOnDelay._171_SECONDS, (byte)-85);
      domainSwitchOnDelays.put(SwitchOnDelay._172_SECONDS, (byte)-84);
      domainSwitchOnDelays.put(SwitchOnDelay._173_SECONDS, (byte)-83);
      domainSwitchOnDelays.put(SwitchOnDelay._174_SECONDS, (byte)-82);
      domainSwitchOnDelays.put(SwitchOnDelay._175_SECONDS, (byte)-81);
      domainSwitchOnDelays.put(SwitchOnDelay._176_SECONDS, (byte)-80);
      domainSwitchOnDelays.put(SwitchOnDelay._177_SECONDS, (byte)-79);
      domainSwitchOnDelays.put(SwitchOnDelay._178_SECONDS, (byte)-78);
      domainSwitchOnDelays.put(SwitchOnDelay._179_SECONDS, (byte)-77);
      domainSwitchOnDelays.put(SwitchOnDelay._180_SECONDS, (byte)-76);
      domainSwitchOnDelays.put(SwitchOnDelay._181_SECONDS, (byte)-75);
      domainSwitchOnDelays.put(SwitchOnDelay._182_SECONDS, (byte)-74);
      domainSwitchOnDelays.put(SwitchOnDelay._183_SECONDS, (byte)-73);
      domainSwitchOnDelays.put(SwitchOnDelay._184_SECONDS, (byte)-72);
      domainSwitchOnDelays.put(SwitchOnDelay._185_SECONDS, (byte)-71);
      domainSwitchOnDelays.put(SwitchOnDelay._186_SECONDS, (byte)-70);
      domainSwitchOnDelays.put(SwitchOnDelay._187_SECONDS, (byte)-69);
      domainSwitchOnDelays.put(SwitchOnDelay._188_SECONDS, (byte)-68);
      domainSwitchOnDelays.put(SwitchOnDelay._189_SECONDS, (byte)-67);
      domainSwitchOnDelays.put(SwitchOnDelay._190_SECONDS, (byte)-66);
      domainSwitchOnDelays.put(SwitchOnDelay._191_SECONDS, (byte)-65);
      domainSwitchOnDelays.put(SwitchOnDelay._192_SECONDS, (byte)-64);
      domainSwitchOnDelays.put(SwitchOnDelay._193_SECONDS, (byte)-63);
      domainSwitchOnDelays.put(SwitchOnDelay._194_SECONDS, (byte)-62);
      domainSwitchOnDelays.put(SwitchOnDelay._195_SECONDS, (byte)-61);
      domainSwitchOnDelays.put(SwitchOnDelay._196_SECONDS, (byte)-60);
      domainSwitchOnDelays.put(SwitchOnDelay._197_SECONDS, (byte)-59);
      domainSwitchOnDelays.put(SwitchOnDelay._198_SECONDS, (byte)-58);
      domainSwitchOnDelays.put(SwitchOnDelay._199_SECONDS, (byte)-57);
      domainSwitchOnDelays.put(SwitchOnDelay._200_SECONDS, (byte)-56);
      domainSwitchOnDelays.put(SwitchOnDelay._201_SECONDS, (byte)-55);
      domainSwitchOnDelays.put(SwitchOnDelay._202_SECONDS, (byte)-54);
      domainSwitchOnDelays.put(SwitchOnDelay._203_SECONDS, (byte)-53);
      domainSwitchOnDelays.put(SwitchOnDelay._204_SECONDS, (byte)-52);
      domainSwitchOnDelays.put(SwitchOnDelay._205_SECONDS, (byte)-51);
      domainSwitchOnDelays.put(SwitchOnDelay._206_SECONDS, (byte)-50);
      domainSwitchOnDelays.put(SwitchOnDelay._207_SECONDS, (byte)-49);
      domainSwitchOnDelays.put(SwitchOnDelay._208_SECONDS, (byte)-48);
      domainSwitchOnDelays.put(SwitchOnDelay._209_SECONDS, (byte)-47);
      domainSwitchOnDelays.put(SwitchOnDelay._210_SECONDS, (byte)-46);
      domainSwitchOnDelays.put(SwitchOnDelay._211_SECONDS, (byte)-45);
      domainSwitchOnDelays.put(SwitchOnDelay._212_SECONDS, (byte)-44);
      domainSwitchOnDelays.put(SwitchOnDelay._213_SECONDS, (byte)-43);
      domainSwitchOnDelays.put(SwitchOnDelay._214_SECONDS, (byte)-42);
      domainSwitchOnDelays.put(SwitchOnDelay._215_SECONDS, (byte)-41);
      domainSwitchOnDelays.put(SwitchOnDelay._216_SECONDS, (byte)-40);
      domainSwitchOnDelays.put(SwitchOnDelay._217_SECONDS, (byte)-39);
      domainSwitchOnDelays.put(SwitchOnDelay._218_SECONDS, (byte)-38);
      domainSwitchOnDelays.put(SwitchOnDelay._219_SECONDS, (byte)-37);
      domainSwitchOnDelays.put(SwitchOnDelay._220_SECONDS, (byte)-36);
      domainSwitchOnDelays.put(SwitchOnDelay._221_SECONDS, (byte)-35);
      domainSwitchOnDelays.put(SwitchOnDelay._222_SECONDS, (byte)-34);
      domainSwitchOnDelays.put(SwitchOnDelay._223_SECONDS, (byte)-33);
      domainSwitchOnDelays.put(SwitchOnDelay._224_SECONDS, (byte)-32);
      domainSwitchOnDelays.put(SwitchOnDelay._225_SECONDS, (byte)-31);
      domainSwitchOnDelays.put(SwitchOnDelay._226_SECONDS, (byte)-30);
      domainSwitchOnDelays.put(SwitchOnDelay._227_SECONDS, (byte)-29);
      domainSwitchOnDelays.put(SwitchOnDelay._228_SECONDS, (byte)-28);
      domainSwitchOnDelays.put(SwitchOnDelay._229_SECONDS, (byte)-27);
      domainSwitchOnDelays.put(SwitchOnDelay._230_SECONDS, (byte)-26);
      domainSwitchOnDelays.put(SwitchOnDelay._231_SECONDS, (byte)-25);
      domainSwitchOnDelays.put(SwitchOnDelay._232_SECONDS, (byte)-24);
      domainSwitchOnDelays.put(SwitchOnDelay._233_SECONDS, (byte)-23);
      domainSwitchOnDelays.put(SwitchOnDelay._234_SECONDS, (byte)-22);
      domainSwitchOnDelays.put(SwitchOnDelay._235_SECONDS, (byte)-21);
      domainSwitchOnDelays.put(SwitchOnDelay._236_SECONDS, (byte)-20);
      domainSwitchOnDelays.put(SwitchOnDelay._237_SECONDS, (byte)-19);
      domainSwitchOnDelays.put(SwitchOnDelay._238_SECONDS, (byte)-18);
      domainSwitchOnDelays.put(SwitchOnDelay._239_SECONDS, (byte)-17);
      domainSwitchOnDelays.put(SwitchOnDelay._240_SECONDS, (byte)-16);
      domainSwitchOnDelays.put(SwitchOnDelay._241_SECONDS, (byte)-15);
      domainSwitchOnDelays.put(SwitchOnDelay._242_SECONDS, (byte)-14);
      domainSwitchOnDelays.put(SwitchOnDelay._243_SECONDS, (byte)-13);
      domainSwitchOnDelays.put(SwitchOnDelay._244_SECONDS, (byte)-12);
      domainSwitchOnDelays.put(SwitchOnDelay._245_SECONDS, (byte)-11);
      domainSwitchOnDelays.put(SwitchOnDelay._246_SECONDS, (byte)-10);
      domainSwitchOnDelays.put(SwitchOnDelay._247_SECONDS, (byte)-9);
      domainSwitchOnDelays.put(SwitchOnDelay._248_SECONDS, (byte)-8);
      domainSwitchOnDelays.put(SwitchOnDelay._249_SECONDS, (byte)-7);
      domainSwitchOnDelays.put(SwitchOnDelay._250_SECONDS, (byte)-6);
      domainSwitchOnDelays.put(SwitchOnDelay._251_SECONDS, (byte)-5);
      domainSwitchOnDelays.put(SwitchOnDelay._252_SECONDS, (byte)-4);
      domainSwitchOnDelays.put(SwitchOnDelay._253_SECONDS, (byte)-3);
      domainSwitchOnDelays.put(SwitchOnDelay._254_SECONDS, (byte)-2);
      domainSwitchOnDelays.put(SwitchOnDelay._255_SECONDS, (byte)-1);
   }
}
