/*
 * Decompiled with CFR 0.152.
 */
package org.apereo.cas.audit;

public interface AuditActionResolvers {
    public static final String REQUEST_FORGOT_USERNAME_ACTION_RESOLVER = "REQUEST_FORGOT_USERNAME_ACTION_RESOLVER";
    public static final String DELEGATED_CLIENT_ACTION_RESOLVER = "DELEGATED_CLIENT_ACTION_RESOLVER";
    public static final String SAVE_CONSENT_ACTION_RESOLVER = "SAVE_CONSENT_ACTION_RESOLVER";
    public static final String ADAPTIVE_RISKY_AUTHENTICATION_ACTION_RESOLVER = "ADAPTIVE_RISKY_AUTHENTICATION_ACTION_RESOLVER";
    public static final String AUP_VERIFY_ACTION_RESOLVER = "AUP_VERIFY_ACTION_RESOLVER";
    public static final String AUP_SUBMIT_ACTION_RESOLVER = "AUP_SUBMIT_ACTION_RESOLVER";
    public static final String CHANGE_PASSWORD_ACTION_RESOLVER = "CHANGE_PASSWORD_ACTION_RESOLVER";
    public static final String REQUEST_CHANGE_PASSWORD_ACTION_RESOLVER = "REQUEST_CHANGE_PASSWORD_ACTION_RESOLVER";
    public static final String REST_API_TICKET_GRANTING_TICKET_ACTION_RESOLVER = "REST_API_TICKET_GRANTING_TICKET_ACTION_RESOLVER";
    public static final String REST_API_SERVICE_TICKET_ACTION_RESOLVER = "REST_API_SERVICE_TICKET_ACTION_RESOLVER";
    public static final String SAML2_RESPONSE_ACTION_RESOLVER = "SAML2_RESPONSE_ACTION_RESOLVER";
    public static final String SAML2_REQUEST_ACTION_RESOLVER = "SAML2_REQUEST_ACTION_RESOLVER";
    public static final String TRUSTED_AUTHENTICATION_ACTION_RESOLVER = "TRUSTED_AUTHENTICATION_ACTION_RESOLVER";
    public static final String MULTIFACTOR_AUTHENTICATION_BYPASS_ACTION_RESOLVER = "MULTIFACTOR_AUTHENTICATION_BYPASS_ACTION_RESOLVER";
    public static final String SURROGATE_AUTHENTICATION_ELIGIBILITY_VERIFICATION_ACTION_RESOLVER = "SURROGATE_AUTHENTICATION_ELIGIBILITY_VERIFICATION_ACTION_RESOLVER";
    public static final String SURROGATE_AUTHENTICATION_ELIGIBILITY_SELECTION_ACTION_RESOLVER = "SURROGATE_AUTHENTICATION_ELIGIBILITY_SELECTION_ACTION_RESOLVER";
    public static final String OAUTH2_USER_PROFILE_ACTION_RESOLVER = "OAUTH2_USER_PROFILE_ACTION_RESOLVER";
    public static final String OAUTH2_ACCESS_TOKEN_REQUEST_ACTION_RESOLVER = "OAUTH2_ACCESS_TOKEN_REQUEST_ACTION_RESOLVER";
    public static final String OAUTH2_ACCESS_TOKEN_RESPONSE_ACTION_RESOLVER = "OAUTH2_ACCESS_TOKEN_RESPONSE_ACTION_RESOLVER";
    public static final String OAUTH2_CODE_RESPONSE_ACTION_RESOLVER = "OAUTH2_CODE_RESPONSE_ACTION_RESOLVER";
    public static final String AUTHENTICATION_RESOLVER = "AUTHENTICATION_RESOLVER";
    public static final String SAVE_SERVICE_ACTION_RESOLVER = "SAVE_SERVICE_ACTION_RESOLVER";
    public static final String DELETE_SERVICE_ACTION_RESOLVER = "DELETE_SERVICE_ACTION_RESOLVER";
    public static final String DESTROY_TICKET_RESOLVER = "DESTROY_TICKET_RESOLVER";
    public static final String DESTROY_PROXY_GRANTING_TICKET_RESOLVER = "DESTROY_PROXY_GRANTING_TICKET_RESOLVER";
    public static final String CREATE_PROXY_GRANTING_TICKET_RESOLVER = "CREATE_PROXY_GRANTING_TICKET_RESOLVER";
    public static final String GRANT_SERVICE_TICKET_RESOLVER = "GRANT_SERVICE_TICKET_RESOLVER";
    public static final String GRANT_PROXY_TICKET_RESOLVER = "GRANT_PROXY_TICKET_RESOLVER";
    public static final String CREATE_TICKET_GRANTING_TICKET_RESOLVER = "CREATE_TICKET_GRANTING_TICKET_RESOLVER";
    public static final String AUTHENTICATION_EVENT_ACTION_RESOLVER = "AUTHENTICATION_EVENT_ACTION_RESOLVER";
    public static final String VALIDATE_SERVICE_TICKET_RESOLVER = "VALIDATE_SERVICE_TICKET_RESOLVER";
    public static final String VALIDATE_PROTOCOL_SPECIFICATION_RESOLVER = "VALIDATE_PROTOCOL_SPECIFICATION_RESOLVER";
    public static final String SERVICE_ACCESS_ENFORCEMENT_ACTION_RESOLVER = "SERVICE_ACCESS_ENFORCEMENT_ACTION_RESOLVER";
    public static final String ACCOUNT_REGISTRATION_TOKEN_CREATION_ACTION_RESOLVER = "ACCOUNT_REGISTRATION_TOKEN_CREATION_ACTION_RESOLVER";
    public static final String ACCOUNT_REGISTRATION_TOKEN_VALIDATION_ACTION_RESOLVER = "ACCOUNT_REGISTRATION_TOKEN_VALIDATION_ACTION_RESOLVER";
    public static final String ACCOUNT_REGISTRATION_PROVISIONING_ACTION_RESOLVER = "ACCOUNT_REGISTRATION_PROVISIONING_ACTION_RESOLVER";
    public static final String LOGOUT_ACTION_RESOLVER = "LOGOUT_ACTION_RESOLVER";
}

