/*
 * Decompiled with CFR 0.152.
 */
package org.htng._2011b;

import com.tpvision.smartinstall.dao.core.GuestInfo;
import com.tpvision.smartinstall.pms.PmsUtils;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import org.dom4j.Element;
import org.htng._2011b.HTNGComponentRoomType;
import org.htng._2011b.HTNGComponentRoomsType;
import org.htng._2011b.HTNGGuestAndRoomStatusService;
import org.htng._2011b.HTNGHelper;
import org.htng._2011b.HTNGHotelRoomStatusSearchRQ;
import org.htng._2011b.HTNGHotelRoomStatusSearchRS;
import org.htng._2011b.HTNGHotelRoomStatusUpdateNotifRQ;
import org.htng._2011b.HTNGHousekeepingStatusType;
import org.htng._2011b.HTNGRequestBaseType;
import org.htng._2011b.HTNGResponseBaseType;
import org.htng._2011b.HTNGRoomElementType;
import org.htng._2011b.HTNGTelephoneExtensionType;
import org.htng._2011b.RoomStatusManagement;
import org.opentravel.ota._2003._05.AdditionalDetailsType;
import org.opentravel.ota._2003._05.CompanyNameType;
import org.opentravel.ota._2003._05.HotelReservationsType;
import org.opentravel.ota._2003._05.POSType;
import org.opentravel.ota._2003._05.ParagraphType;
import org.opentravel.ota._2003._05.RoomTypeType;
import org.opentravel.ota._2003._05.SourceType;
import org.opentravel.ota._2003._05.TPAExtensionsType;
import org.opentravel.ota._2003._05.UniqueIDType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public final class RoomStatusManagementClient {
    private static final Logger LOG = LoggerFactory.getLogger(RoomStatusManagementClient.class);
    private static final QName SERVICE_NAME = new QName("http://htng.org/2011B", "HTNG_GuestAndRoomStatusService");
    private String wsdl;
    private RoomStatusManagement port;

    public RoomStatusManagement getPort() {
        if (this.port == null) {
            HTNGGuestAndRoomStatusService ss = new HTNGGuestAndRoomStatusService();
            this.port = ss.getRoomStatusManagement();
            BindingProvider bp = (BindingProvider)((Object)this.port);
            bp.getRequestContext().put("javax.xml.ws.service.endpoint.address", this.wsdl);
        }
        return this.port;
    }

    public void connect() {
        this.port = null;
        this.getPort();
    }

    public RoomStatusManagementClient(String wsdl) {
        this.wsdl = wsdl;
    }

    public void refresh(String roomid) {
        LOG.info("request refresh:{}", (Object)roomid);
        HTNGHotelRoomStatusSearchRQ request = new HTNGHotelRoomStatusSearchRQ();
        if (roomid == null) {
            roomid = "All";
        }
        request.setRoom(HTNGHelper.generateRoom(roomid));
        HTNGHotelRoomStatusSearchRS searchRooms = this.port.searchRooms(request);
        for (HTNGHotelRoomStatusSearchRS.RoomInformationList.RoomInformation roominfo : searchRooms.getRoomInformationList().getRoomInformation()) {
            roomid = roominfo.getRoom().getRoomID();
            LOG.info("handling room:{}", (Object)roomid);
            for (HotelReservationsType.HotelReservation res : roominfo.getHotelReservations().getHotelReservation()) {
                try {
                    if ("Checked In".equalsIgnoreCase(res.getResStatus())) {
                        Element rootElt = HTNGHelper.getElementFromReservation(res, roominfo.getRoom().getRoomID());
                        GuestInfo guest = PmsUtils.saveCheckinResults2DB(rootElt);
                        PmsUtils.checkin2TV(guest, true);
                        continue;
                    }
                    PmsUtils.processCheckout(roomid);
                }
                catch (IOException e) {
                    LOG.error(e.getMessage(), e);
                }
            }
        }
    }

    public static void main(String[] args) throws Exception {
        URL wsdlURL = HTNGGuestAndRoomStatusService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                wsdlURL = wsdlFile.exists() ? wsdlFile.toURI().toURL() : new URL(args[0]);
            }
            catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
        HTNGGuestAndRoomStatusService ss = new HTNGGuestAndRoomStatusService(wsdlURL, SERVICE_NAME);
        RoomStatusManagement port = ss.getRoomStatusManagement();
        System.out.println("Invoking searchRooms...");
        HTNGHotelRoomStatusSearchRQ _searchRooms_htngHotelRoomStatusSearchRQ = new HTNGHotelRoomStatusSearchRQ();
        POSType _searchRooms_htngHotelRoomStatusSearchRQPOS = new POSType();
        ArrayList<SourceType> _searchRooms_htngHotelRoomStatusSearchRQPOSSource = new ArrayList<SourceType>();
        SourceType _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1 = new SourceType();
        SourceType.RequestorID _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorID = new SourceType.RequestorID();
        CompanyNameType _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorIDCompanyName = new CompanyNameType();
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorIDCompanyName.setValue("Value-195658287");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorIDCompanyName.setDivision("Division930118813");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorIDCompanyName.setDepartment("Department1554233794");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorIDCompanyName.setCompanyShortName("CompanyShortName-329948012");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorIDCompanyName.setTravelSector("TravelSector-1564966465");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorIDCompanyName.setCode("Code-950197625");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorIDCompanyName.setCodeContext("CodeContext660553862");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorID.setCompanyName(_searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorIDCompanyName);
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorID.setURL("URL-447642972");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorID.setType("Type-893197653");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorID.setInstance("Instance-379525751");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorID.setIDContext("IDContext923096501");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorID.setID("ID1621133965");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorID.setMessagePassword("MessagePassword71107167");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1.setRequestorID(_searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1RequestorID);
        SourceType.Position _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1Position = new SourceType.Position();
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1Position.setLatitude("Latitude-524299420");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1Position.setLongitude("Longitude-1671534658");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1Position.setAltitude("Altitude-319862976");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1Position.setAltitudeUnitOfMeasureCode("AltitudeUnitOfMeasureCode1781016147");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1Position.setPositionAccuracy("PositionAccuracy-1344525354");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1.setPosition(_searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1Position);
        SourceType.BookingChannel _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1BookingChannel = new SourceType.BookingChannel();
        CompanyNameType _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1BookingChannelCompanyName = new CompanyNameType();
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1BookingChannelCompanyName.setValue("Value-2125580982");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1BookingChannelCompanyName.setDivision("Division-195513085");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1BookingChannelCompanyName.setDepartment("Department-1860994682");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1BookingChannelCompanyName.setCompanyShortName("CompanyShortName-82862121");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1BookingChannelCompanyName.setTravelSector("TravelSector953865508");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1BookingChannelCompanyName.setCode("Code-847668141");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1BookingChannelCompanyName.setCodeContext("CodeContext-338831472");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1BookingChannel.setCompanyName(_searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1BookingChannelCompanyName);
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1BookingChannel.setType("Type860012832");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1BookingChannel.setPrimary(true);
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1.setBookingChannel(_searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1BookingChannel);
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1.setAgentSine("AgentSine-1083672827");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1.setPseudoCityCode("PseudoCityCode-1459571464");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1.setISOCountry("ISOCountry588080620");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1.setISOCurrency("ISOCurrency-1435332045");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1.setAgentDutyCode("AgentDutyCode1633944493");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1.setAirlineVendorID("AirlineVendorID-517949246");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1.setAirportCode("AirportCode-1802304255");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1.setFirstDepartPoint("FirstDepartPoint1887531738");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1.setERSPUserID("ERSPUserID-1890768060");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1.setTerminalID("TerminalID500554572");
        _searchRooms_htngHotelRoomStatusSearchRQPOSSource.add(_searchRooms_htngHotelRoomStatusSearchRQPOSSourceVal1);
        _searchRooms_htngHotelRoomStatusSearchRQPOS.getSource().addAll(_searchRooms_htngHotelRoomStatusSearchRQPOSSource);
        _searchRooms_htngHotelRoomStatusSearchRQ.setPOS(_searchRooms_htngHotelRoomStatusSearchRQPOS);
        UniqueIDType _searchRooms_htngHotelRoomStatusSearchRQUniqueID = new UniqueIDType();
        CompanyNameType _searchRooms_htngHotelRoomStatusSearchRQUniqueIDCompanyName = new CompanyNameType();
        _searchRooms_htngHotelRoomStatusSearchRQUniqueIDCompanyName.setValue("Value-939897359");
        _searchRooms_htngHotelRoomStatusSearchRQUniqueIDCompanyName.setDivision("Division1087135580");
        _searchRooms_htngHotelRoomStatusSearchRQUniqueIDCompanyName.setDepartment("Department-1775821564");
        _searchRooms_htngHotelRoomStatusSearchRQUniqueIDCompanyName.setCompanyShortName("CompanyShortName-741990822");
        _searchRooms_htngHotelRoomStatusSearchRQUniqueIDCompanyName.setTravelSector("TravelSector2056225181");
        _searchRooms_htngHotelRoomStatusSearchRQUniqueIDCompanyName.setCode("Code728974422");
        _searchRooms_htngHotelRoomStatusSearchRQUniqueIDCompanyName.setCodeContext("CodeContext2049098902");
        _searchRooms_htngHotelRoomStatusSearchRQUniqueID.setCompanyName(_searchRooms_htngHotelRoomStatusSearchRQUniqueIDCompanyName);
        _searchRooms_htngHotelRoomStatusSearchRQUniqueID.setURL("URL-1563741585");
        _searchRooms_htngHotelRoomStatusSearchRQUniqueID.setType("Type-1315614982");
        _searchRooms_htngHotelRoomStatusSearchRQUniqueID.setInstance("Instance-1785454971");
        _searchRooms_htngHotelRoomStatusSearchRQUniqueID.setIDContext("IDContext-395772305");
        _searchRooms_htngHotelRoomStatusSearchRQUniqueID.setID("ID-129196706");
        _searchRooms_htngHotelRoomStatusSearchRQ.setUniqueID(_searchRooms_htngHotelRoomStatusSearchRQUniqueID);
        HTNGRequestBaseType.PropertyInfo _searchRooms_htngHotelRoomStatusSearchRQPropertyInfo = new HTNGRequestBaseType.PropertyInfo();
        _searchRooms_htngHotelRoomStatusSearchRQPropertyInfo.setChainCode("ChainCode-1044367337");
        _searchRooms_htngHotelRoomStatusSearchRQPropertyInfo.setBrandCode("BrandCode-582576776");
        _searchRooms_htngHotelRoomStatusSearchRQPropertyInfo.setHotelCode("HotelCode-869716361");
        _searchRooms_htngHotelRoomStatusSearchRQPropertyInfo.setHotelCityCode("HotelCityCode-1191365089");
        _searchRooms_htngHotelRoomStatusSearchRQPropertyInfo.setHotelName("HotelName-778779810");
        _searchRooms_htngHotelRoomStatusSearchRQPropertyInfo.setHotelCodeContext("HotelCodeContext-559280762");
        _searchRooms_htngHotelRoomStatusSearchRQPropertyInfo.setChainName("ChainName-1096278805");
        _searchRooms_htngHotelRoomStatusSearchRQPropertyInfo.setBrandName("BrandName-1412167194");
        _searchRooms_htngHotelRoomStatusSearchRQPropertyInfo.setAreaID("AreaID-1985938151");
        _searchRooms_htngHotelRoomStatusSearchRQ.setPropertyInfo(_searchRooms_htngHotelRoomStatusSearchRQPropertyInfo);
        _searchRooms_htngHotelRoomStatusSearchRQ.setEchoToken("EchoToken-2073139967");
        _searchRooms_htngHotelRoomStatusSearchRQ.setTimeStamp(DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-24T09:54:33.580+08:00"));
        _searchRooms_htngHotelRoomStatusSearchRQ.setTarget("Target-278577789");
        _searchRooms_htngHotelRoomStatusSearchRQ.setTargetName("TargetName-1660551567");
        _searchRooms_htngHotelRoomStatusSearchRQ.setVersion(new BigDecimal("-4751846023464300373.6497221837016450465"));
        _searchRooms_htngHotelRoomStatusSearchRQ.setTransactionIdentifier("TransactionIdentifier-1852906159");
        _searchRooms_htngHotelRoomStatusSearchRQ.setSequenceNmbr(new BigInteger("9709604756027596779145955750072109799"));
        _searchRooms_htngHotelRoomStatusSearchRQ.setTransactionStatusCode("TransactionStatusCode1515605301");
        _searchRooms_htngHotelRoomStatusSearchRQ.setRetransmissionIndicator(true);
        _searchRooms_htngHotelRoomStatusSearchRQ.setCorrelationID("CorrelationID-1543610799");
        _searchRooms_htngHotelRoomStatusSearchRQ.setPrimaryLangID("PrimaryLangID-666451474");
        _searchRooms_htngHotelRoomStatusSearchRQ.setAltLangID("AltLangID-1513570984");
        HTNGComponentRoomType _searchRooms_htngHotelRoomStatusSearchRQRoom = new HTNGComponentRoomType();
        RoomTypeType _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType = new RoomTypeType();
        ParagraphType _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeRoomDescription = new ParagraphType();
        ArrayList _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeRoomDescriptionTextOrImageOrURL = new ArrayList();
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeRoomDescription.getTextOrImageOrURL().addAll(_searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeRoomDescriptionTextOrImageOrURL);
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeRoomDescription.setName("Name1413529164");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeRoomDescription.setParagraphNumber(new BigInteger("88560141214248539026797247019572798860"));
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeRoomDescription.setCreateDateTime(DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-24T09:54:33.582+08:00"));
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeRoomDescription.setCreatorID("CreatorID-1964147638");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeRoomDescription.setLastModifyDateTime(DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-24T09:54:33.583+08:00"));
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeRoomDescription.setLastModifierID("LastModifierID956738855");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeRoomDescription.setPurgeDate(DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-24T09:54:33.583+08:00"));
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeRoomDescription.setLanguage("Language1293049392");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setRoomDescription(_searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeRoomDescription);
        AdditionalDetailsType _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeAdditionalDetails = new AdditionalDetailsType();
        ArrayList _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeAdditionalDetailsAdditionalDetail = new ArrayList();
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeAdditionalDetails.getAdditionalDetail().addAll(_searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeAdditionalDetailsAdditionalDetail);
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setAdditionalDetails(_searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeAdditionalDetails);
        RoomTypeType.Amenities _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeAmenities = new RoomTypeType.Amenities();
        ArrayList _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeAmenitiesAmenity = new ArrayList();
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeAmenities.getAmenity().addAll(_searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeAmenitiesAmenity);
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setAmenities(_searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeAmenities);
        ArrayList _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeOccupancy = new ArrayList();
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.getOccupancy().addAll(_searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeOccupancy);
        TPAExtensionsType _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeTPAExtensions = new TPAExtensionsType();
        ArrayList _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeTPAExtensionsAny = new ArrayList();
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeTPAExtensions.getAny().addAll(_searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeTPAExtensionsAny);
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setTPAExtensions(_searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeTPAExtensions);
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setNumberOfUnits(new BigInteger("-6967259166775568962553976853800019137"));
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setIsRoom(false);
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setIsConverted(true);
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setIsAlternate(false);
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setReqdGuaranteeType("ReqdGuaranteeType1671307906");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setRoomType("RoomType-1909832271");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setRoomTypeCode("RoomTypeCode1141619467");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setRoomCategory("RoomCategory-1361542874");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setRoomID("RoomID1236765316");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setFloor(347785496);
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setInvBlockCode("InvBlockCode-135580330");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setRoomLocationCode("RoomLocationCode1428963411");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setRoomViewCode("RoomViewCode107119252");
        ArrayList _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeBedTypeCode = new ArrayList();
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.getBedTypeCode().addAll(_searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypeBedTypeCode);
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setNonSmoking(false);
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setConfiguration("Configuration1877969446");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setSizeMeasurement("SizeMeasurement-1787256656");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setQuantity(-2142547016);
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setComposite(true);
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setRoomClassificationCode("RoomClassificationCode359164023");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setRoomArchitectureCode("RoomArchitectureCode-1898620348");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setRoomGender("RoomGender1164836066");
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setSharedRoomInd(true);
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.setPromotionCode("PromotionCode-1347793603");
        ArrayList _searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypePromotionVendorCode = new ArrayList();
        _searchRooms_htngHotelRoomStatusSearchRQRoomRoomType.getPromotionVendorCode().addAll(_searchRooms_htngHotelRoomStatusSearchRQRoomRoomTypePromotionVendorCode);
        _searchRooms_htngHotelRoomStatusSearchRQRoom.setRoomType(_searchRooms_htngHotelRoomStatusSearchRQRoomRoomType);
        HTNGTelephoneExtensionType _searchRooms_htngHotelRoomStatusSearchRQRoomTelephoneExtensions = new HTNGTelephoneExtensionType();
        ArrayList _searchRooms_htngHotelRoomStatusSearchRQRoomTelephoneExtensionsTelephoneExtention = new ArrayList();
        _searchRooms_htngHotelRoomStatusSearchRQRoomTelephoneExtensions.getTelephoneExtention().addAll(_searchRooms_htngHotelRoomStatusSearchRQRoomTelephoneExtensionsTelephoneExtention);
        _searchRooms_htngHotelRoomStatusSearchRQRoom.setTelephoneExtensions(_searchRooms_htngHotelRoomStatusSearchRQRoomTelephoneExtensions);
        HTNGHousekeepingStatusType _searchRooms_htngHotelRoomStatusSearchRQRoomHKStatus = HTNGHousekeepingStatusType.OFF_MARKET;
        _searchRooms_htngHotelRoomStatusSearchRQRoom.setHKStatus(_searchRooms_htngHotelRoomStatusSearchRQRoomHKStatus);
        TPAExtensionsType _searchRooms_htngHotelRoomStatusSearchRQRoomTPAExtensions = new TPAExtensionsType();
        ArrayList _searchRooms_htngHotelRoomStatusSearchRQRoomTPAExtensionsAny = new ArrayList();
        _searchRooms_htngHotelRoomStatusSearchRQRoomTPAExtensions.getAny().addAll(_searchRooms_htngHotelRoomStatusSearchRQRoomTPAExtensionsAny);
        _searchRooms_htngHotelRoomStatusSearchRQRoom.setTPAExtensions(_searchRooms_htngHotelRoomStatusSearchRQRoomTPAExtensions);
        _searchRooms_htngHotelRoomStatusSearchRQRoom.setRoomID("RoomID-205332895");
        _searchRooms_htngHotelRoomStatusSearchRQ.setRoom(_searchRooms_htngHotelRoomStatusSearchRQRoom);
        TPAExtensionsType _searchRooms_htngHotelRoomStatusSearchRQTPAExtensions = new TPAExtensionsType();
        ArrayList<org.w3c.dom.Element> _searchRooms_htngHotelRoomStatusSearchRQTPAExtensionsAny = new ArrayList<>();
        org.w3c.dom.Element _searchRooms_htngHotelRoomStatusSearchRQTPAExtensionsAnyVal1 = null;
        _searchRooms_htngHotelRoomStatusSearchRQTPAExtensionsAny.add(_searchRooms_htngHotelRoomStatusSearchRQTPAExtensionsAnyVal1);
        _searchRooms_htngHotelRoomStatusSearchRQTPAExtensions.getAny().addAll(_searchRooms_htngHotelRoomStatusSearchRQTPAExtensionsAny);
        _searchRooms_htngHotelRoomStatusSearchRQ.setTPAExtensions(_searchRooms_htngHotelRoomStatusSearchRQTPAExtensions);
        HTNGHotelRoomStatusSearchRS _searchRooms__return = port.searchRooms(_searchRooms_htngHotelRoomStatusSearchRQ);
        System.out.println("searchRooms.result=" + _searchRooms__return);
        System.out.println("Invoking updateRoomStatus...");
        HTNGHotelRoomStatusUpdateNotifRQ _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ = new HTNGHotelRoomStatusUpdateNotifRQ();
        POSType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOS = new POSType();
        ArrayList<SourceType> _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSource = new ArrayList<SourceType>();
        SourceType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1 = new SourceType();
        SourceType.RequestorID _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorID = new SourceType.RequestorID();
        CompanyNameType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorIDCompanyName = new CompanyNameType();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorIDCompanyName.setValue("Value1390948565");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorIDCompanyName.setDivision("Division-317497856");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorIDCompanyName.setDepartment("Department1097199566");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorIDCompanyName.setCompanyShortName("CompanyShortName-1538905958");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorIDCompanyName.setTravelSector("TravelSector-342195697");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorIDCompanyName.setCode("Code-1494558546");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorIDCompanyName.setCodeContext("CodeContext-52454973");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorID.setCompanyName(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorIDCompanyName);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorID.setURL("URL2071658999");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorID.setType("Type-1309975769");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorID.setInstance("Instance304557228");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorID.setIDContext("IDContext1062269880");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorID.setID("ID-551118818");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorID.setMessagePassword("MessagePassword1545760407");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1.setRequestorID(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1RequestorID);
        SourceType.Position _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1Position = new SourceType.Position();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1Position.setLatitude("Latitude458494253");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1Position.setLongitude("Longitude1358466046");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1Position.setAltitude("Altitude-1810984858");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1Position.setAltitudeUnitOfMeasureCode("AltitudeUnitOfMeasureCode240179194");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1Position.setPositionAccuracy("PositionAccuracy-980210489");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1.setPosition(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1Position);
        SourceType.BookingChannel _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1BookingChannel = new SourceType.BookingChannel();
        CompanyNameType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1BookingChannelCompanyName = new CompanyNameType();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1BookingChannelCompanyName.setValue("Value270810320");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1BookingChannelCompanyName.setDivision("Division-1555461242");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1BookingChannelCompanyName.setDepartment("Department-706943059");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1BookingChannelCompanyName.setCompanyShortName("CompanyShortName1363616323");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1BookingChannelCompanyName.setTravelSector("TravelSector-1057219946");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1BookingChannelCompanyName.setCode("Code-999837553");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1BookingChannelCompanyName.setCodeContext("CodeContext-91454285");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1BookingChannel.setCompanyName(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1BookingChannelCompanyName);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1BookingChannel.setType("Type128063156");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1BookingChannel.setPrimary(true);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1.setBookingChannel(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1BookingChannel);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1.setAgentSine("AgentSine-1012632805");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1.setPseudoCityCode("PseudoCityCode163137753");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1.setISOCountry("ISOCountry-95550262");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1.setISOCurrency("ISOCurrency-646574896");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1.setAgentDutyCode("AgentDutyCode11667654");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1.setAirlineVendorID("AirlineVendorID2103950106");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1.setAirportCode("AirportCode-1829342873");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1.setFirstDepartPoint("FirstDepartPoint1053714643");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1.setERSPUserID("ERSPUserID1992442333");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1.setTerminalID("TerminalID-122860476");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSource.add(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSourceVal1);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOS.getSource().addAll(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOSSource);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setPOS(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPOS);
        UniqueIDType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueID = new UniqueIDType();
        CompanyNameType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueIDCompanyName = new CompanyNameType();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueIDCompanyName.setValue("Value182474099");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueIDCompanyName.setDivision("Division113337138");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueIDCompanyName.setDepartment("Department2021112149");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueIDCompanyName.setCompanyShortName("CompanyShortName-882443813");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueIDCompanyName.setTravelSector("TravelSector2016825580");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueIDCompanyName.setCode("Code-492855827");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueIDCompanyName.setCodeContext("CodeContext1436913662");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueID.setCompanyName(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueIDCompanyName);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueID.setURL("URL1929165628");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueID.setType("Type175930176");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueID.setInstance("Instance-967525368");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueID.setIDContext("IDContext-596433160");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueID.setID("ID722214149");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setUniqueID(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQUniqueID);
        HTNGRequestBaseType.PropertyInfo _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPropertyInfo = new HTNGRequestBaseType.PropertyInfo();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPropertyInfo.setChainCode("ChainCode-486513442");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPropertyInfo.setBrandCode("BrandCode2113078673");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPropertyInfo.setHotelCode("HotelCode651988325");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPropertyInfo.setHotelCityCode("HotelCityCode160870068");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPropertyInfo.setHotelName("HotelName374283786");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPropertyInfo.setHotelCodeContext("HotelCodeContext2055653344");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPropertyInfo.setChainName("ChainName1876923744");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPropertyInfo.setBrandName("BrandName754394765");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPropertyInfo.setAreaID("AreaID1241798384");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setPropertyInfo(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQPropertyInfo);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setEchoToken("EchoToken76084768");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setTimeStamp(DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-24T09:54:33.593+08:00"));
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setTarget("Target-63912916");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setTargetName("TargetName-391487551");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setVersion(new BigDecimal("-2602257067293225458.2905544893619738316"));
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setTransactionIdentifier("TransactionIdentifier-312968856");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setSequenceNmbr(new BigInteger("27912521032472112991501255714412344598"));
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setTransactionStatusCode("TransactionStatusCode506806569");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setRetransmissionIndicator(true);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setCorrelationID("CorrelationID-1998564099");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setPrimaryLangID("PrimaryLangID258393503");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setAltLangID("AltLangID420668187");
        HTNGRoomElementType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoom = new HTNGRoomElementType();
        RoomTypeType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType = new RoomTypeType();
        ParagraphType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeRoomDescription = new ParagraphType();
        ArrayList _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeRoomDescriptionTextOrImageOrURL = new ArrayList();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeRoomDescription.getTextOrImageOrURL().addAll(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeRoomDescriptionTextOrImageOrURL);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeRoomDescription.setName("Name2138114123");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeRoomDescription.setParagraphNumber(new BigInteger("-81745053858193879895773505271208081692"));
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeRoomDescription.setCreateDateTime(DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-24T09:54:33.594+08:00"));
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeRoomDescription.setCreatorID("CreatorID1794123712");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeRoomDescription.setLastModifyDateTime(DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-24T09:54:33.595+08:00"));
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeRoomDescription.setLastModifierID("LastModifierID-972346750");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeRoomDescription.setPurgeDate(DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-24T09:54:33.595+08:00"));
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeRoomDescription.setLanguage("Language917096796");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setRoomDescription(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeRoomDescription);
        AdditionalDetailsType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeAdditionalDetails = new AdditionalDetailsType();
        ArrayList _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeAdditionalDetailsAdditionalDetail = new ArrayList();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeAdditionalDetails.getAdditionalDetail().addAll(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeAdditionalDetailsAdditionalDetail);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setAdditionalDetails(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeAdditionalDetails);
        RoomTypeType.Amenities _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeAmenities = new RoomTypeType.Amenities();
        ArrayList _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeAmenitiesAmenity = new ArrayList();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeAmenities.getAmenity().addAll(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeAmenitiesAmenity);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setAmenities(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeAmenities);
        ArrayList _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeOccupancy = new ArrayList();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.getOccupancy().addAll(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeOccupancy);
        TPAExtensionsType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeTPAExtensions = new TPAExtensionsType();
        ArrayList _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeTPAExtensionsAny = new ArrayList();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeTPAExtensions.getAny().addAll(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeTPAExtensionsAny);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setTPAExtensions(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeTPAExtensions);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setNumberOfUnits(new BigInteger("58243190916054292201815319109739938858"));
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setIsRoom(false);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setIsConverted(true);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setIsAlternate(true);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setReqdGuaranteeType("ReqdGuaranteeType-1252592330");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setRoomType("RoomType-1828403139");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setRoomTypeCode("RoomTypeCode1093157493");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setRoomCategory("RoomCategory873217594");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setRoomID("RoomID844044650");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setFloor(-875910201);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setInvBlockCode("InvBlockCode701384051");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setRoomLocationCode("RoomLocationCode1910426858");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setRoomViewCode("RoomViewCode-360008420");
        ArrayList _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeBedTypeCode = new ArrayList();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.getBedTypeCode().addAll(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypeBedTypeCode);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setNonSmoking(false);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setConfiguration("Configuration-1315747930");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setSizeMeasurement("SizeMeasurement1293735167");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setQuantity(880208112);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setComposite(false);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setRoomClassificationCode("RoomClassificationCode-873883882");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setRoomArchitectureCode("RoomArchitectureCode1519048365");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setRoomGender("RoomGender-1337490166");
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setSharedRoomInd(true);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.setPromotionCode("PromotionCode1857322981");
        ArrayList _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypePromotionVendorCode = new ArrayList();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType.getPromotionVendorCode().addAll(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomTypePromotionVendorCode);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoom.setRoomType(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomRoomType);
        HTNGTelephoneExtensionType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomTelephoneExtensions = new HTNGTelephoneExtensionType();
        ArrayList _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomTelephoneExtensionsTelephoneExtention = new ArrayList();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomTelephoneExtensions.getTelephoneExtention().addAll(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomTelephoneExtensionsTelephoneExtention);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoom.setTelephoneExtensions(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomTelephoneExtensions);
        HTNGHousekeepingStatusType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomHKStatus = HTNGHousekeepingStatusType.NEEDS_INSPECTION;
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoom.setHKStatus(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomHKStatus);
        TPAExtensionsType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomTPAExtensions = new TPAExtensionsType();
        ArrayList _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomTPAExtensionsAny = new ArrayList();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomTPAExtensions.getAny().addAll(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomTPAExtensionsAny);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoom.setTPAExtensions(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomTPAExtensions);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoom.setRoomID("RoomID659396818");
        HTNGComponentRoomsType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomComponentRooms = new HTNGComponentRoomsType();
        ArrayList _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomComponentRoomsComponentRoom = new ArrayList();
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomComponentRooms.getComponentRoom().addAll(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomComponentRoomsComponentRoom);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoom.setComponentRooms(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoomComponentRooms);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setRoom(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQRoom);
        TPAExtensionsType _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQTPAExtensions = new TPAExtensionsType();
        ArrayList<org.w3c.dom.Element> _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQTPAExtensionsAny = new ArrayList<>();
        org.w3c.dom.Element _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQTPAExtensionsAnyVal1 = null;
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQTPAExtensionsAny.add(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQTPAExtensionsAnyVal1);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQTPAExtensions.getAny().addAll(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQTPAExtensionsAny);
        _updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ.setTPAExtensions(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQTPAExtensions);
        HTNGResponseBaseType _updateRoomStatus__return = port.updateRoomStatus(_updateRoomStatus_htngHotelRoomStatusUpdateNotifRQ);
        System.out.println("updateRoomStatus.result=" + _updateRoomStatus__return);
        System.exit(0);
    }
}
